<a href="https://colab.research.google.com/github/junsookim76/Ewha_2025/blob/main/2_Numpy_Updated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

> Import "numpy"
>
> The fundamental package for scientific computing with Python


In [ ]:
import numpy as np

import matplotlib.pyplot as plt
import sys,os,copy,random,math
%matplotlib inline

## **1. Introducing numpy array**

In [ ]:
array=[1,2,3,4,5,6,7,8]

print(array)
print(type(array))
print(len(array))

numpy_array=np.array(array)
print(type(numpy_array))
print(numpy_array)
print(numpy_array.dtype)
print(numpy_array.shape)

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>
8
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]
int64
(8,)


In [ ]:
array2=2*array

print(array)
print(array2)

numpy_array2=2*numpy_array
print(numpy_array)
print(numpy_array2)


[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]
[ 2  4  6  8 10 12 14 16]


In [ ]:
numpy_array3=np.array([1,2,3,4,5,6,7,8])
print(type(numpy_array3))
print(numpy_array3)
print(numpy_array3.dtype)
print(numpy_array3.shape)


<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]
int64
(8,)


In [ ]:
numpy_array4=np.arange(1,9)
print(type(numpy_array4))
print(numpy_array4)
print(numpy_array4.dtype)
print(numpy_array4.shape)


<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]
int64
(8,)


## **2. Change array shape**

In [ ]:
new_array=np.reshape(array,(2,4))
print(new_array)
print(new_array.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
new_array=np.reshape(array,(2,-1))
print(new_array)

[[1 2 3 4]
 [5 6 7 8]]


## **3.Indexing and slicing**

In [ ]:
print(new_array[1,2])
print(new_array[1][2])

7
7


In [ ]:
new_array[1,:]

array([5, 6, 7, 8])

In [ ]:
new_array[0,::2]

array([1, 3])

In [ ]:
new_array[0,1::2]

array([2, 4])

In [ ]:
array2=new_array[:,:2]
array2

array([[1, 2],
       [5, 6]])

In [ ]:
new2=np.zeros((8,8))
new2

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
new2[2::3,4::2]=array2
new2

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 6., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
print(new_array)
new_array>2

[[1 2 3 4]
 [5 6 7 8]]


array([[False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
new_array[new_array>2]

array([3, 4, 5, 6, 7, 8])

## **4.Calculation**

In [ ]:
new_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
new_array+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [ ]:
new_array/new_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.sum(new_array,axis=0)

array([ 6,  8, 10, 12])

In [ ]:
np.sum(new_array,axis=1)

array([10, 26])

In [ ]:
new_array[0]

array([1, 2, 3, 4])

In [ ]:
np.dot(new_array[0],new_array[1])

70

## **5. Input & Output**

In [ ]:
np.savetxt("data.txt",new_array)

In [ ]:
array=np.loadtxt("data.txt")
array

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [ ]:
print(array[0])
print(array[:,1])

[1. 2. 3. 4.]
[2. 6.]


## **6. Math Functions and Symbols**

In [ ]:
np.pi

3.141592653589793

In [ ]:
theta=np.arange(0,2*np.pi,np.pi/10)
print(type(theta))
print(theta)
print(theta.shape)

<class 'numpy.ndarray'>
[0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604]
20
(20,)


In [ ]:
np.sin(theta)

array([ 0.00000000e+00,  3.09016994e-01,  5.87785252e-01,  8.09016994e-01,
        9.51056516e-01,  1.00000000e+00,  9.51056516e-01,  8.09016994e-01,
        5.87785252e-01,  3.09016994e-01,  1.22464680e-16, -3.09016994e-01,
       -5.87785252e-01, -8.09016994e-01, -9.51056516e-01, -1.00000000e+00,
       -9.51056516e-01, -8.09016994e-01, -5.87785252e-01, -3.09016994e-01])