<a href="https://colab.research.google.com/github/junsookim76/Ewha_2023/blob/main/2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# "Import" numpy and etc

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import sys,os,copy,random,math
%matplotlib inline 

# Create numpy array

In [ ]:
array=[1,2,3,4,5,6,7,8]
numpy_array=np.array(array)
print(type(array))
print(type(numpy_array))
print(numpy_array)
print(numpy_array.dtype)
print(numpy_array.shape)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]
int64
(8,)


# Change array shape

In [ ]:
new_array=np.reshape(array,(2,4))
print(new_array)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
new_array=np.reshape(array,(2,-1))
print(new_array)

[[1 2 3 4]
 [5 6 7 8]]


# Indexing and slicing

In [ ]:
print(new_array[1,2])
print(new_array[1][2])

7
7


In [ ]:
new_array[1,:]

array([5, 6, 7, 8])

In [ ]:
new_array[0,::2]

array([1, 3])

In [ ]:
new_array[0,1::2]

array([2, 4])

In [ ]:
array2=new_array[:,:2]
array2

array([[1, 2],
       [5, 6]])

In [ ]:
new2=np.zeros((8,8))
new2

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
new2[2::3,4::2]=array2
new2

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 6., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
new_array>2

array([[False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
new_array[new_array>2]

array([3, 4, 5, 6, 7, 8])

# Calculation

In [ ]:
new_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
new_array+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [ ]:
new_array/new_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.sum(new_array,axis=0)

array([ 6,  8, 10, 12])

In [ ]:
np.sum(new_array,axis=1)

array([10, 26])

In [ ]:
new_array[0]

array([1, 2, 3, 4])

In [ ]:
np.dot(new_array[0],new_array[1])

70

# File IO

In [ ]:
np.savetxt("data.txt",new_array)

In [ ]:
np.loadtxt("data.txt")

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

# Pi / Math Functions

In [ ]:
np.pi

3.141592653589793

In [ ]:
theta=np.arange(0,2*np.pi,np.pi/10)
print(type(theta))
print(theta)

<class 'numpy.ndarray'>
[0.         0.31415927 0.62831853 0.9424778  1.25663706 1.57079633
 1.88495559 2.19911486 2.51327412 2.82743339 3.14159265 3.45575192
 3.76991118 4.08407045 4.39822972 4.71238898 5.02654825 5.34070751
 5.65486678 5.96902604]


In [ ]:
np.sin(theta)

array([ 0.00000000e+00,  3.09016994e-01,  5.87785252e-01,  8.09016994e-01,
        9.51056516e-01,  1.00000000e+00,  9.51056516e-01,  8.09016994e-01,
        5.87785252e-01,  3.09016994e-01,  1.22464680e-16, -3.09016994e-01,
       -5.87785252e-01, -8.09016994e-01, -9.51056516e-01, -1.00000000e+00,
       -9.51056516e-01, -8.09016994e-01, -5.87785252e-01, -3.09016994e-01])